# Generated by Django 4.0 on 2022-07-06 11:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorial_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
