# Generated by Django 4.0 on 2022-07-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorial_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcionalidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='avaliacaotutorial',
            name='avaliacao',
            field=models.IntegerField(verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacaotutorial',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial'),
        ),
        migrations.AlterField(
            model_name='avaliacaotutorial',
            name='text',
            field=models.CharField(max_length=40, verbose_name='Descrição da avaliação'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='aplicacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutorials.aplicacaotutorial'),
            preserve_default=False,
        ),
    ]
