# Generated by Django 4.0 on 2022-07-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
        ('tutorials', '0004_aplicacaotutorial_alter_avaliacaotutorial_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.aplicacaotutorial'),
        ),
        migrations.DeleteModel(
            name='AplicacaoTutorial',
        ),
    ]
